// ─────────────────────────────────────────────────────────────────────────────
//  PyWeb Academy — Date cursuri statice
// ─────────────────────────────────────────────────────────────────────────────

export const COURSES = [
  {
    slug: 'python-fundamentals',
    level: 'Începător',
    levelColor: '#22c55e',
    levelBg: '#f0fdf4',
    title: 'Python Fundamentals',
    subtitle: 'Primul pas în lumea programării',
    desc: 'Bazele programării cu Python — variabile, condiții, bucle, funcții. Copilul creează primele sale programe și jocuri simple.',
    longDesc: 'Cursul Python Fundamentals este conceput special pentru adolescenți fără experiență anterioară. Prin proiecte practice și jocuri, copiii descoperă logica programării și capătă încredere în abilitățile lor. La final, fiecare cursant prezintă un proiect propriu creat de la zero.',
    duration: '6 luni',
    age: '12–14 ani',
    groupSize: 'Max 10 elevi',
    sessionsPerWeek: '2 ședințe/săptămână',
    sessionLength: '90 min/ședință',
    price: '1200 MDL/lună',
    image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1200&q=80',
    color: '#22c55e',
    topics: ['Variabile & tipuri', 'Funcții', 'Jocuri simple', 'Proiect final'],
    curriculum: [
      { week: 'Lunile 1–2', title: 'Bazele Python', items: ['Instalare & mediu de lucru', 'Variabile, tipuri de date', 'Operatori și expresii', 'Input/Output'] },
      { week: 'Lunile 2–3', title: 'Condiții & bucle', items: ['if / elif / else', 'Bucle for și while', 'Liste și dicționare', 'Mini-joc text aventură'] },
      { week: 'Lunile 3–4', title: 'Funcții & module', items: ['Definirea funcțiilor', 'Parametri & return', 'Module standard Python', 'Turtle Graphics'] },
      { week: 'Lunile 4–5', title: 'Proiecte practice', items: ['Joc Snake simplificat', 'Calculator avansat', 'Quiz interactiv', 'Sortare & algoritmi de bază'] },
      { week: 'Luna 6', title: 'Proiect final', items: ['Alegerea temei', 'Dezvoltare ghidată', 'Prezentare & diplomă', 'Portofoliu GitHub'] },
    ],
    benefits: [
      'Gândire logică și rezolvare de probleme',
      'Primul proiect real pe GitHub',
      'Diplomă PyWeb Academy',
      'Bază solidă pentru cursurile avansate',
    ],
    forWho: 'Cursul este ideal pentru adolescenți de 12–14 ani, fără orice experiență anterioară în programare. Tot ce au nevoie este curiozitate și un laptop!',
  },
  {
    slug: 'web-development',
    level: 'Intermediar',
    levelColor: '#3b82f6',
    levelBg: '#eff6ff',
    title: 'Web Development',
    subtitle: 'Creează site-uri reale de la zero',
    desc: 'HTML, CSS și JavaScript de la zero. Adolescenții construiesc site-uri reale, responsive, cu animații și interactivitate.',
    longDesc: 'Cursul Web Development acoperă întregul stack front-end modern: de la structura HTML, la designul cu CSS și interactivitatea cu JavaScript. La final, fiecare cursant are un portofoliu online real cu minim 3 proiecte publice.',
    duration: '6 luni',
    age: '13–16 ani',
    groupSize: 'Max 10 elevi',
    sessionsPerWeek: '2 ședințe/săptămână',
    sessionLength: '90 min/ședință',
    price: '1300 MDL/lună',
    image: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=1200&q=80',
    color: '#3b82f6',
    topics: ['HTML & CSS', 'JavaScript', 'Design responsiv', 'Portofoliu online'],
    curriculum: [
      { week: 'Lunile 1–2', title: 'HTML & CSS', items: ['Structura paginilor web', 'CSS: culori, fonturi, layout', 'Flexbox & Grid', 'Primul site personal'] },
      { week: 'Lunile 2–3', title: 'CSS avansat', items: ['Animații CSS', 'Responsive design', 'Media queries', 'Design cu Figma (intro)'] },
      { week: 'Lunile 3–4', title: 'JavaScript', items: ['Variabile, funcții, evenimente', 'DOM manipulation', 'Fetch API & JSON', 'Mini-aplicație interactivă'] },
      { week: 'Lunile 4–5', title: 'Proiecte reale', items: ['Clonă landing page', 'Aplicație To-Do', 'Weather App cu API', 'Optimizare & performanță'] },
      { week: 'Luna 6', title: 'Portofoliu & lansare', items: ['Deploy pe Vercel/Netlify', 'Domeniu personalizat', 'Prezentare publică', 'Certificat & diplomă'] },
    ],
    benefits: [
      'Portofoliu online cu proiecte reale',
      'Cunoștințe HTML, CSS, JS moderne',
      'Deploy live — site-ul tău pe internet',
      'Diplomă PyWeb Academy',
    ],
    forWho: 'Recomandat pentru adolescenți de 13–16 ani cu minim cunoștințe de bază IT. Nu e obligatorie experiența în programare, dar ajută cunoașterea bazică a unui calculator.',
  },
  {
    slug: 'ai-machine-learning',
    level: 'Avansat',
    levelColor: '#8b5cf6',
    levelBg: '#f5f3ff',
    title: 'AI & Machine Learning',
    subtitle: 'Inteligența artificială pentru tineri',
    desc: 'Inteligență artificială aplicată — modele ML, procesare de imagini și text. Proiecte care impresionează la admitere.',
    longDesc: 'Cel mai avansat curs PyWeb Academy. Elevii înțeleg cum funcționează AI-ul din spatele ChatGPT, cum se antrenează modele ML și cum să construiască aplicații AI reale. Proiectul final poate fi inclus în dosarul de admitere la universitate.',
    duration: '6 luni',
    age: '15–18 ani',
    groupSize: 'Max 10 elevi',
    sessionsPerWeek: '2 ședințe/săptămână',
    sessionLength: '90 min/ședință',
    price: '1500 MDL/lună',
    image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200&q=80',
    color: '#8b5cf6',
    topics: ['Python avansat', 'Scikit-learn', 'Rețele neurale', 'Proiect AI real'],
    curriculum: [
      { week: 'Lunile 1–2', title: 'Python avansat & date', items: ['NumPy & Pandas', 'Vizualizare cu Matplotlib', 'Curățarea datelor', 'Statistică aplicată'] },
      { week: 'Lunile 2–3', title: 'Machine Learning', items: ['Regresie liniară & logistică', 'Arbori de decizie', 'Scikit-learn toolkit', 'Evaluarea modelelor'] },
      { week: 'Lunile 3–4', title: 'Deep Learning', items: ['Rețele neurale artificiale', 'TensorFlow / Keras intro', 'Clasificare imagini CNN', 'Transfer learning'] },
      { week: 'Lunile 4–5', title: 'NLP & AI aplicat', items: ['Procesarea textului (NLP)', 'Sentiment analysis', 'Intro LLM & prompt engineering', 'API-uri AI (OpenAI, HuggingFace)'] },
      { week: 'Luna 6', title: 'Proiect AI final', items: ['Temă la alegere', 'Mentoring 1-la-1', 'Prezentare publică', 'Certificat & recomandare'] },
    ],
    benefits: [
      'Proiect AI real pentru portofoliu/admitere',
      'Cunoștințe ML/DL căutate pe piață',
      'Certificat avansat PyWeb Academy',
      'Scrisoare de recomandare',
    ],
    forWho: 'Cursul este dedicat adolescenților de 15–18 ani cu experiență solidă în Python (sau absolvirea cursului Python Fundamentals). Ideal pentru cei care vizează facultăți de informatică sau o carieră în tech.',
  },
]

export function getCourseBySlug(slug) {
  return COURSES.find((c) => c.slug === slug) || null
}
